export const SET_ARTICLE_COLLECTION = 'SET_ARTICLE_COLLECTION';
export const SET_ARTICLE = 'SET_ARTICLE';
export const SET_FILTERS = 'SET_FILTERS';
export const SET_PAGINATION = 'SET_PAGINATION';
export const SET_LOADING = 'SET_LOADING';
export const SET_TOGGLE_CLASS = 'SET_TOGGLE_CLASS';
